disabled_rules: # rule identifiers to exclude from running
  - convenience_type
  - todo
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
opt_in_rules: # some rules are only opt-in
  - attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - control_statement
  - discouraged_direct_init
  - discouraged_optional_boolean
  - double_space
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - modifier_order
  - private_action
  - private_outlet
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xctfail_message
  - yoda_condition
included: # paths to include during linting. `--path` is ignored if present.
  - weg-li
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Playgrounds
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
cyclomatic_complexity:
  ignores_case_statements: true
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# they can set both implicitly with an array
large_tuple:
  - 4
type_body_length:
  - 300 # warning
  - 400 # error
function_parameter_count:
  - 6
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
line_length: 180
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    warning: 1
  excluded: # excluded via string array
    - sut
    - id
    - URL
    - to
    - T
    - x
    - y
custom_rules:
  double_space:
    include: "*.swift"
    name: "Double space"
    regex: "([a-z,A-Z] \\s+)"
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)